### ISSUE TITLE
Compilation documentation?

### ISSUE THREAD

**Issue by virtuald** [tumagonx/pygi-mingw-patches#2]
How do I compile my own version of the installer, is it documented anywhere?

**Comment by tumagonx** [comment]
If you just want to repack the binaries see https://sourceforge.net/p/pygobjectwin32/tickets/19/
the installer itself is driven by batch file "setup.bat" and using zenity as gui (all files available in "setup" subdirectory after executing unpack.bat)

**Comment by virtuald** [comment]
I would like to build new binaries.

**Comment by tumagonx** [comment]
http://opensourcepack.blogspot.com/2013/11/how-to-build-pygi-aio-with-moluccas.html
If you don't need the customized MSYS just download the gcc only it can be used in MSYS2/Cygwin

**Comment by virtuald** [comment]
Thanks.

**Comment by tumagonx** [comment]
I made the compiler available at pygobject's SF for convenience
