### ISSUE TITLE
can't find glib_get_locale_dir()

### ISSUE THREAD

**Issue by jcupitt** [tumagonx/pygi-mingw-patches#5]
Hi! 

I'm trying to fold your great vips patches into libvips master, but I'm being dumb, I can't find the source for glib_get_locale_dir(). Could you point me towards it?

I have this so far:

https://github.com/jcupitt/libvips/commit/ba129fceb3e4e0f6f33677bb2d5579130c179793

**Comment by tumagonx** [comment]
ahh my bad habit, ever since glib drop the use of .def files that private _glib_get_locale_dir() get exported in dll, and since I'm too lazy wrote proper dllmain()->g_win32_get_package_installation_directory_of_module() stuff I always call that convenient function 
it should be like:
```
#ifdef G_OS_WIN32
#include <windows.h>
HMODULE vips_dll = NULL;
#ifdef DLL_EXPORT
BOOL WINAPI
DllMain (HINSTANCE hinstDLL,
	 DWORD     fdwReason,
	 LPVOID    lpvReserved)
{
  if (fdwReason == DLL_PROCESS_ATTACH)
      vips_dll = hinstDLL;

  return TRUE;
}
#endif
#endif
...
#ifdef _WIN32
	localedir = g_build_filename(g_win32_get_package_installation_directory_of_module(vips_dll),"share","locale",NULL));
	bindtextdomain (GETTEXT_PACKAGE, localedir);
	g_free (localedir);
#else
 	bindtextdomain( GETTEXT_PACKAGE, name );
#endif
```

**Comment by jcupitt** [comment]
That's great! Thanks, copypasted in.

**Comment by jcupitt** [comment]
(I've not been able to actually test on win, but hopefully it'll work)

**Comment by jcupitt** [comment]
I improved it a bit. Thank you again for fixing this dumbness.
